### ISSUE TITLE
0.1: Create page layout sketches

### ISSUE THREAD

**Issue by Rds1055** [Rds1055/fall-22-dbgui#56]

**Comment by mswigart** [comment]
[Create Post.pdf](https://github.com/Rds1055/fall-22-dbgui/files/9821966/Create.Post.pdf)
[Homepage.pdf](https://github.com/Rds1055/fall-22-dbgui/files/9821967/Homepage.pdf)

**Comment by camrose00** [comment]
[post : questions.pdf](https://github.com/Rds1055/fall-22-dbgui/files/9823753/post.questions.pdf)

**Comment by MichaelLCastle** [comment]
[SearchBarSketches.pdf](https://github.com/Rds1055/fall-22-dbgui/files/9824531/SearchBarSketches.pdf)
